### ISSUE TITLE
remove demo videos, add real demo to gh-pages

### ISSUE THREAD

**Issue by milahu** [RoyNij/svelte-d3#12]
... ideally remove videos from all the git history

**Comment by RoyNij** [comment]
@milahu Thanks for the heads up, that is a good point. Haven't had time to create a decent demo yet. Will start working on one, in the meantime if you want you can see a production version on: https://knowledge4recovery.org/country-profiles/

**Comment by RoyNij** [comment]
Now a storybook demo available in the gh-pages, for now not removing the gifs from the git history
